package com.test.before.interview.Database.Model;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER".
*/
public class UserDao extends AbstractDao<User, Long> {

    public static final String TABLENAME = "USER";

    /**
     * Properties of entity User.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "Id", true, "_id");
        public final static Property Username = new Property(1, String.class, "Username", false, "USERNAME");
        public final static Property AvatarURL = new Property(2, String.class, "AvatarURL", false, "AVATAR_URL");
        public final static Property HtmlURL = new Property(3, String.class, "HtmlURL", false, "HTML_URL");
        public final static Property CreateAt = new Property(4, int.class, "CreateAt", false, "CREATE_AT");
    }


    public UserDao(DaoConfig config) {
        super(config);
    }
    
    public UserDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: Id
                "\"USERNAME\" TEXT," + // 1: Username
                "\"AVATAR_URL\" TEXT," + // 2: AvatarURL
                "\"HTML_URL\" TEXT," + // 3: HtmlURL
                "\"CREATE_AT\" INTEGER NOT NULL );"); // 4: CreateAt
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, User entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String Username = entity.getUsername();
        if (Username != null) {
            stmt.bindString(2, Username);
        }
 
        String AvatarURL = entity.getAvatarURL();
        if (AvatarURL != null) {
            stmt.bindString(3, AvatarURL);
        }
 
        String HtmlURL = entity.getHtmlURL();
        if (HtmlURL != null) {
            stmt.bindString(4, HtmlURL);
        }
        stmt.bindLong(5, entity.getCreateAt());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, User entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String Username = entity.getUsername();
        if (Username != null) {
            stmt.bindString(2, Username);
        }
 
        String AvatarURL = entity.getAvatarURL();
        if (AvatarURL != null) {
            stmt.bindString(3, AvatarURL);
        }
 
        String HtmlURL = entity.getHtmlURL();
        if (HtmlURL != null) {
            stmt.bindString(4, HtmlURL);
        }
        stmt.bindLong(5, entity.getCreateAt());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public User readEntity(Cursor cursor, int offset) {
        User entity = new User( //
            cursor.getLong(offset + 0), // Id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // Username
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // AvatarURL
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // HtmlURL
            cursor.getInt(offset + 4) // CreateAt
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, User entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setUsername(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAvatarURL(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setHtmlURL(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCreateAt(cursor.getInt(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(User entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(User entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(User entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
